name: Daily Task

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  at:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate
        uses: Zxilly/animated-timeline@master
        with:
          output: 'falldown.webp'
          type: 'webp'
          login: 'Zxilly'
      
      - name: Commit
        run: |
          curl -H "Authorization: $TOKEN" -T falldown.webp https://image.zxilly.dev/falldown.webp
        env:
          TOKEN: ${{ secrets.TOKEN }}
          
  waka:
    runs-on: ubuntu-latest
    steps:
    - name: Update gist
      uses: matchai/waka-box@master
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: 40fabe4fbc612208eee108087d745c49
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
